### ISSUE TITLE
想封装一层，hook类方法时崩溃

### ISSUE THREAD

**Issue by liyongjie1002** [xindizhiyin2014/JKUBSAspects#1]
想对您的库封装下，老是报错
unrecognized selector sent to class 0x10539c3b8
能帮忙看下么？[https://github.com/Iyongjie/MDAspects](demo) 谢谢🙏

**Comment by liyongjie1002** [comment]
demo地址。https://github.com/Iyongjie/MDAspects

**Comment by xindizhiyin2014** [comment]
你好，你加一下我的QQ吧 929097264

发自我的 iPhone

**Comment by liyongjie1002** [comment]
ok，已加
